### ISSUE TITLE
Propulsion.EventStore.Reader vs EventStore's subscriptions

### ISSUE THREAD

**Issue by dharmaturtle** [jet/propulsion#87]
EventStore [has subscriptions](https://eventstore.com/docs/getting-started/reading-subscribing-events/index.html?tabs=tabid-6%2Ctabid-dotnet-read-event%2Ctabid-create-sub-dotnet#subscription-types). My belief is that this is achieved without polling.  

`Propulsion.EventStore.Reader` [polls](https://github.com/jet/propulsion/blob/da479eaeec931d44c4ecbfeb8313a326eca7e209/src/Propulsion.EventStore/EventStoreReader.fs#L269).

Imagine there's a (not necessarily Propulsion) Reactor that's updating a read model. My understanding is that it would be better to use EventStore's native subscriptions instead of `Propulsion.EventStore.Reader` as it would be faster _and_ use less compute. Are there reasons to choose `Propulsion.EventStore.Reader` other than "stats"?

Note: A comment on `EventStoreReader.exec` states "can have parallel invocations". However, EventStore's persistent subscriptions allows for [competing consumers](https://eventstore.com/docs/dotnet-api/competing-consumers/index.html), which I think is more or less the same thing.

**Comment by bartelink** [comment]
I'm no expert on the trade-offs of ReadAllStreamEvents vs subscriptions.

While polling in general is frowned on, RASE is pretty damn efficient in terms of its impl in EventStore (i.e. stuff is cached, the protocol makes it efficient etc)

But really, the main reason it's used in Propulsion is that the usage scenarios we needed to support closely matched the what RASE can provide (the general stream scheduler was first implemented for CFP and Kafka consumption scenarios).

I'd definitely do some research (maybe via the DDD-CQRS-ES slack) about pros and cons of subscriptions before selecting it over RASE (i.e. does it work well with clusters, is it supported in v20 or being deprecated etc)
